#!/usr/bin/env bash
#
#  find-genstrings.sh
#  Shared
#
#  Created by Michael Reneer on 2/10/16.
#  Copyright © 2016 Michael Reneer. All rights reserved.
#

source_dir="${SOURCE_ROOT}/${PROJECT_NAME}"
find ${source_dir} -name "*.[m|mm|swift]" -print0 | xargs -0 genstrings -o "${source_dir}/en.lproj"
